repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer

  # - repo: https://github.com/pycqa/flake8
  #   rev: 7.0.0
  #   hooks:
  #     - id: flake8
  #       additional_dependencies: [flake8-docstrings]

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args: ['--line-length', '79']
