repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer

  # - repo: https://github.com/pycqa/flake8
  #   rev: 7.0.0
  #   hooks:
  #     - id: flake8
  #       additional_dependencies: [flake8-docstrings]

  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        args: ['--line-length', '79']

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.0.0'  # Specify the latest ESLint mirror release or use 'master'
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@^8.57.0  # Specify the version of ESLint you have installed
        args:
          - '--max-warnings=0'  # Fails if there are warnings
        files: \.(js|jsx|ts|tsx)$  # Adjust this regex to target specific files
